---
- name: Setup motd on linux boxes
  copy:
    content: "ILS WORKSHOPS - ANSIBLE when test"
    dest: "/etc/motd"
  register: var_motd

- name: debug output
  debug:
    var: var_motd
  when: 
    - var_motd.changed == true
    - var_motd.changed

- name: create file
  file:
    path: /tmp/temp
    state: absent

- name: stat file
  stat: 
    path: /tmp/temp
  register: __var_stat

- name: file delete without module but with tests
  command: "rm /tmp/temp" 
  when: __var_stat.stat.exists == true
  #ignore_errors: true
  #failed_when: false
  #changed_when: false

- debug:
    msg: "another task"

